2024-10-07 10:28:20,931 | INFO | "test_run" выполнен успешно
2024-10-07 10:28:20,931 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\project\Python lessons\Modul 12\resolve4.py", line 74, in test_run
    run_2 = Runner(5)
            ^^^^^^^^^
  File "C:\project\Python lessons\Modul 12\resolve4.py", line 15, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-07 10:28:20,932 | INFO | "test_walk" выполнен успешно
2024-10-07 10:28:20,932 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\project\Python lessons\Modul 12\resolve4.py", line 64, in test_walk
    run_1 = Runner('Vlad', -5)
            ^^^^^^^^^^^^^^^^^^
  File "C:\project\Python lessons\Modul 12\resolve4.py", line 20, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
